/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f407xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	uint32_t delay;
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIODEN;
	GPIOD->MODER |= GPIO_MODER_MODER12_0;
	GPIOD->MODER &= ~GPIO_MODER_MODER12_1;
	GPIOD->OTYPER &= ~GPIO_OTYPER_OT12;
	GPIOD->OSPEEDR &= ~(GPIO_OSPEEDR_OSPEED12_0 | GPIO_OSPEEDR_OSPEED12_1);
	GPIOD->PUPDR &= ~GPIO_PUPDR_PUPD12_Msk;

    /* Loop forever */
	for(;;) {
		for (delay = 0; delay < 200000; delay++);
		GPIOD->BSRR |= GPIO_BSRR_BR12;
		for (delay = 0; delay<200000; delay++);
		GPIOD->BSRR |= GPIO_BSRR_BS12;
	}
}
